### ISSUE TITLE
Seems like it can't handle .d.ts files

### ISSUE THREAD

**Issue by aa-ihorskliar** [R-Mielamud/TsUnited#1]
I have in my tsconfig.json:
```
"typeRoots": ["node_modules/@types", "src/types"],
```

and have a file `src/types.d.ts` which contains global types like:
```
declare global {
	interface Window {
		customProp: string;
	}
}
```

and when I use ` tsu-node ./index.ts` it works well before I import the file which trying to use that `Window['customProp']` as type, then I get errors:
```
error TS2339: Property 'customProp' does not exist on type 'Window'.
error TS2339: Property 'customProp' does not exist on type 'Window & typeof globalThis'
```

**Comment by R-Mielamud** [comment]
Hello! Thanks for the contribution :)
Unfortunately,  not handling global types is an issue from `ts-node` library. For optimization it only loads files which are referenced from the file it has to execute in the first place (`index.ts` in this case) or it's imports.
To fix the issue I added an `loadAllFiles` option for each project (node edition). With it enabled all project files are preloaded according to `include`, `exclude` and `files` options in tsconfig.json, thus no global types are lost.
Secondly, there's an issue with your definition: add an `export {};` line in the end. And if you declare variables, just use `declare var myVariable: type` instead of `declare global { ... }`.
